# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_dp_variantcpupython3.7._:
        CONFIG: linux_64_dp_variantcpupython3.7._
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: ghcr.io/deepmd-kit-recipes/linux-anvil-cuda:11.3
      linux_64_dp_variantcpupython3.8._:
        CONFIG: linux_64_dp_variantcpupython3.8._
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: ghcr.io/deepmd-kit-recipes/linux-anvil-cuda:11.3
      linux_64_dp_variantcpupython3.9._:
        CONFIG: linux_64_dp_variantcpupython3.9._
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: ghcr.io/deepmd-kit-recipes/linux-anvil-cuda:11.3
      linux_64_dp_variantgpupython3.7._:
        CONFIG: linux_64_dp_variantgpupython3.7._
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: ghcr.io/deepmd-kit-recipes/linux-anvil-cuda:11.3
      linux_64_dp_variantgpupython3.8._:
        CONFIG: linux_64_dp_variantgpupython3.8._
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: ghcr.io/deepmd-kit-recipes/linux-anvil-cuda:11.3
      linux_64_dp_variantgpupython3.9._:
        CONFIG: linux_64_dp_variantgpupython3.9._
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: ghcr.io/deepmd-kit-recipes/linux-anvil-cuda:11.3
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)